type Category {
  _id: ID
  name: String
  specifications: JSON
  createdDate: Date
  updatedDate: Date
  status: String
}

extend type Query {
  getAllCategories: Response
  getListCategories: [Category]
  getCategory(id: ID): Category
}

extend type Mutation {
  createCategory(params: JSON): Response
}